version: '3.9'

name: p1  

services:
  backend: 
    image: cmtabr/backend-p1
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-p1
    restart: on-failure
    ports: 
      - "5000:5000"
    
  frontend: 
    image: cmtabr/frontend-p1
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-p1
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

