version: '3.9'

name: p1  

services:
  backend: 
    image: p1/backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-p1
    restart: on-failure
    ports: 
      - "5000:5000"
    
  frontend: 
    image: p1/frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-p1
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

