version: '3.9'

services: 
  api: 
    image: cmtabr/api
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports: 
      - "5000:5000"
    volumes: 
      - ./:/app
    depends_on: 
      - database

  database:
    image: cmtabr/db
    build: 
        context: ./database
        dockerfile: Dockerfile
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: banco
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
